import { guide } from "@/lib/health/guide";
import type { HealthGuide } from "@/lib/health/types";

export const CAT_GUIDES: HealthGuide[] = [
  guide({
    slug: "cat-flutd",
    title: "하부요로기질환(FLUTD)",
    species: ["cat"],
    kind: "disease",
    system: "urinary",
    urgency: "emergency",
    summary:
      "방광·요도 자극으로 잦은 배뇨·혈뇨·힘주기가 나타납니다. 수컷 요도폐색은 생명을 위협하는 응급입니다.",
    signals: [
      "화장실을 자주 들락날락",
      "모래 밖에서 배뇨",
      "혈뇨·작은 소변",
      "울면서 힘주기·구토·무기력(폐색 의심)",
    ],
    causes: [
      "특발성 방광염(스트레스)",
      "결정·결석",
      "감염(상대적으로 적음)",
      "물 섭취 부족",
    ],
    homeCare: [
      "물 섭취를 늘리세요(여러 그릇·분수·습식)",
      "화장실 n+1, 청결 유지",
      "스트레스 요인(공사·다묘 갈등) 완화",
    ],
    seeVetWhen: [
      "소변을 전혀 못 봄 — 즉시 응급",
      "반복되는 혈뇨·배뇨통",
      "수컷 고양이 이상 징후",
    ],
    prevention: [
      "습식 급여·수분 관리",
      "환경 풍부화로 스트레스 감소",
      "처방 요로식이는 유형에 맞게",
    ],
    relatedSlugs: ["cat-constipation", "cat-stress-prevention"],
  }),
  guide({
    slug: "cat-ckd",
    title: "만성신부전",
    species: ["cat"],
    kind: "disease",
    system: "urinary",
    urgency: "soon",
    summary:
      "신장 기능이 서서히 떨어지는 노령묘 대표 질환입니다. IRIS 단계에 따라 식이·수액·약물 전략이 달라집니다.",
    signals: [
      "물을 많이 마시고 소변량이 많음",
      "체중·근육 감소",
      "식욕 저하·구토",
      "구취·탈수",
    ],
    causes: [
      "노화·신장 손상 누적",
      "고혈압·감염·독성 물질",
      "일부 선천·유전 요인",
    ],
    homeCare: [
      "처방 신장식·인 관리",
      "수분 섭취 극대화",
      "체중·식욕·음수량을 기록",
    ],
    seeVetWhen: [
      "다갈다뇨·체중 감소",
      "정기 SDMA·크레아티닌·혈압 모니터링",
      "급성 악화(무뇨·심한 구토)",
    ],
    prevention: [
      "중년 이후 정기 혈액·소변 검사",
      "신독성 해열제 등 사람약 금지",
      "치과 감염·탈수 예방",
    ],
    relatedSlugs: ["cat-senior-checkup", "cat-anemia"],
  }),
  guide({
    slug: "cat-hairball",
    title: "헤어볼",
    species: ["cat"],
    kind: "disease",
    system: "digestive",
    urgency: "monitor",
    summary:
      "그루밍한 털이 위에 뭉쳐 구토로 나오는 현상입니다. 잦다면 피부·소화·과잉그루밍 원인을 함께 봅니다.",
    signals: [
      "털 뭉치를 토함",
      "헛구역질·식욕 저하",
      "변비·처짐(드물게 폐색)",
    ],
    causes: [
      "장모·과잉 그루밍",
      "피부 가려움",
      "운동·섬유 부족",
    ],
    homeCare: [
      "정기 빗질",
      "헤어볼 케어 식이/페이스트는 제품 지시 준수",
      "토하는 ‘헤어볼’이 아닌 반복 구토면 병원",
    ],
    seeVetWhen: [
      "구토가 잦고 털이 안 나옴",
      "극심한 무기력·변비·복부 팽만",
    ],
    prevention: [
      "환절기 빗질 강화",
      "놀이로 장운동 촉진",
      "피부 알러지·벼룩 관리",
    ],
    relatedSlugs: ["cat-overgrooming", "cat-vomiting"],
  }),
  guide({
    slug: "cat-stomatitis",
    title: "구내염",
    species: ["cat"],
    kind: "disease",
    system: "dental",
    urgency: "soon",
    summary:
      "입안 점막의 심한 염증으로 통증·침 흘림·식욕 저하가 큽니다. 치과 처치와 면역·바이러스 요인이 복합적입니다.",
    signals: [
      "침 과다·입 냄새",
      "단단한 사료 거부",
      "얼굴을 비비거나 움찔",
      "체중 감소",
    ],
    causes: [
      "치주질환",
      "면역 매개 염증",
      "칼리시·허피스 등 바이러스 연관",
    ],
    homeCare: [
      "부드러운 습식 제공(병원 지시 전)",
      "임의 소독제·사람 구강용품 금지",
    ],
    seeVetWhen: [
      "통증으로 식사를 못할 때",
      "발치·항염 치료 상담",
    ],
    prevention: [
      "정기 구강 검진",
      "치아 위생·스케일링",
      "바이러스 백신·건강관리",
    ],
    relatedSlugs: ["cat-periodontal", "cat-uri"],
  }),
  guide({
    slug: "cat-panleukopenia",
    title: "범백혈구감소증",
    species: ["cat"],
    kind: "disease",
    system: "infectious",
    urgency: "emergency",
    summary:
      "고양이 파보에 해당하는 치명적 감염병입니다. 어린 고양이에서 구토·설사·백혈구 감소가 급격히 진행됩니다.",
    signals: [
      "갑작스러운 구토·설사",
      "고열 후 체온 저하",
      "극심한 무기력·탈수",
    ],
    causes: ["고양이 파보바이러스(FPV)", "미접종·오염 환경"],
    homeCare: ["즉시 병원·격리", "가정 내 소독(수의사 지침)"],
    seeVetWhen: ["의심만으로 응급"],
    prevention: [
      "핵심 백신 스케줄",
      "접종 전 다묘 환경 노출 최소화",
    ],
    relatedSlugs: ["cat-vomiting", "cat-diarrhea", "cat-vaccination"],
  }),
  guide({
    slug: "cat-uri",
    title: "고양이 감기(허피스 등)",
    species: ["cat"],
    kind: "disease",
    system: "respiratory",
    urgency: "soon",
    summary:
      "허피스·칼리시 등 상부기도 감염으로 재채기·콧물·눈곱이 생깁니다. 스트레스 시 잠복 바이러스가 재활성화되기도 합니다.",
    signals: [
      "재채기·콧물",
      "눈곱·결막 충혈",
      "식욕 저하(냄새를 못 맡음)",
      "구강 궤양(칼리시)",
    ],
    causes: [
      "FHV-1·FCV 등",
      "밀집·환기 불량",
      "면역 저하·스트레스",
    ],
    homeCare: [
      "가습·코/눈 분비물 부드럽게 닦기",
      "따뜻하고 냄새 강한 습식으로 식욕 유도",
      "다른 고양이와 격리",
    ],
    seeVetWhen: [
      "호흡곤란·입을 벌리고 숨쉼",
      "탈수·3일 이상 식욕 저하",
      "어린 고양이·만성 재발",
    ],
    prevention: [
      "백신",
      "스트레스·다묘 밀도 관리",
      "새 고양이 검역",
    ],
    relatedSlugs: ["cat-conjunctivitis", "cat-breathing-emergency"],
  }),
  guide({
    slug: "cat-obesity",
    title: "고양이 비만",
    species: ["cat"],
    kind: "disease",
    system: "metabolic",
    urgency: "monitor",
    summary:
      "비만은 당뇨·관절·요로·간지질증 위험을 올립니다. 실내묘·중성화 후 특히 흔합니다.",
    signals: [
      "갈비·허리가 만져지지 않음",
      "그루밍이 힘들어 등쪽 피모 불량",
      "점프를 꺼림",
    ],
    causes: ["과식·자유급식", "운동 부족", "중성화 후 대사 변화"],
    homeCare: [
      "계량 급여·퍼즐 급식기",
      "하루 사냥 놀이 2~3회",
      "급격한 단식 금지(간지질증 위험)",
    ],
    seeVetWhen: [
      "감량 계획·기초질환 검사",
      "식욕 소실이 하루 이상(응급에 가깝)",
    ],
    prevention: [
      "중성화 직후 칼로리 재설정",
      "간식 규칙",
      "체중 월간 기록",
    ],
    relatedSlugs: ["cat-diabetes", "cat-flutd"],
  }),
  guide({
    slug: "cat-diabetes",
    title: "고양이 당뇨",
    species: ["cat"],
    kind: "disease",
    system: "endocrine",
    urgency: "soon",
    summary:
      "다갈다뇨·체중 감소가 전형적입니다. 비만묘에서 흔하고, 조기 관리 시 관해가 가능한 경우도 있습니다.",
    signals: [
      "물·소변량 증가",
      "식욕은 있는데 체중 감소",
      "뒷다리 약화(일부)",
      "무기력",
    ],
    causes: ["인슐린 저항", "비만", "일부 약물·췌장 질환"],
    homeCare: [
      "처방 식이·인슐린 스케줄 엄수",
      "저혈당 증상(떨림·쓰러짐) 교육",
    ],
    seeVetWhen: [
      "다갈다뇨",
      "식욕 소실·구토(케톤산증)",
    ],
    prevention: [
      "비만 예방",
      "고탄수 간식 남용 금지",
      "정기 검진",
    ],
    relatedSlugs: ["cat-obesity", "cat-senior-checkup"],
  }),
  guide({
    slug: "cat-hyperthyroidism",
    title: "갑상선기능항진증",
    species: ["cat"],
    kind: "disease",
    system: "endocrine",
    urgency: "soon",
    summary:
      "노령묘에서 흔한 내분비 질환으로 식욕 증가에도 체중이 줄고, 심박·혈압·구토가 동반될 수 있습니다.",
    signals: [
      "많이 먹는데 야윔",
      "과도한 울음·불안",
      "구토·설사",
      "빠른 심장박동·헐떡임",
    ],
    causes: ["갑상선 조직 과형성/종양"],
    homeCare: [
      "투약·처방식을 규칙적으로",
      "체중·식욕 기록",
    ],
    seeVetWhen: [
      "체중 감소·다갈",
      "심장·혈압 평가 필요",
    ],
    prevention: [
      "7세 이상 정기 T4·혈압 검사",
      "체중 변화 조기 발견",
    ],
    relatedSlugs: ["cat-senior-checkup", "cat-ckd"],
  }),
  guide({
    slug: "cat-periodontal",
    title: "고양이 치주질환",
    species: ["cat"],
    kind: "disease",
    system: "dental",
    urgency: "soon",
    summary:
      "치석·잇몸염은 통증과 전신 염증의 원인이 됩니다. 고양이는 티를 안 내 뒤늦게 발견되는 경우가 많습니다.",
    signals: [
      "입 냄새",
      "침·한쪽으로 씹기",
      "사료를 떨어뜨림",
      "얼굴 부종",
    ],
    causes: ["치태", "구강 해부 구조", "일부 바이러스·면역"],
    homeCare: [
      "가능한 범위에서 양치·덴탈케어",
      "정기 검진으로 ‘숨어있는’ 통증 발견",
    ],
    seeVetWhen: [
      "식욕 저하·구취",
      "스케일링·발치 상담",
    ],
    prevention: [
      "연 1회 구강 평가",
      "적절한 장난감·식이 질감",
    ],
    relatedSlugs: ["cat-stomatitis"],
  }),
  guide({
    slug: "cat-vomiting",
    title: "고양이 구토",
    species: ["cat"],
    kind: "symptom",
    system: "digestive",
    urgency: "soon",
    summary:
      "헤어볼·급식·염증성장·신장·갑상선·이물 등 원인이 다양합니다. ‘자주’와 ‘전신 상태’가 핵심입니다.",
    signals: [
      "음식물/거품/담즙/털",
      "빈도(주 수회 이상이면 정상 아님)",
      "체중·식욕 변화",
    ],
    causes: [
      "헤어볼·급하게 먹음",
      "음식 알러지·IBD",
      "전신질환·이물",
    ],
    homeCare: [
      "토사물·빈도를 기록",
      "퍼즐로 식사 속도 늦추기",
      "사람약 금지",
    ],
    seeVetWhen: [
      "하루 여러 번·혈토·이물",
      "식욕 소실·무기력",
      "어린/노령묘",
    ],
    prevention: [
      "빗질·식이 급변 방지",
      "독성 식물·이물 차단",
      "정기 검진",
    ],
    relatedSlugs: ["cat-hairball", "cat-ckd", "cat-hyperthyroidism"],
  }),
  guide({
    slug: "cat-diarrhea",
    title: "고양이 설사",
    species: ["cat"],
    kind: "symptom",
    system: "digestive",
    urgency: "soon",
    summary:
      "급성은 식이·기생충·감염이, 만성은 염증·식이반응·전신질환이 원인일 수 있습니다.",
    signals: ["무른 변", "점액·혈변", "횟수 증가", "항문 주변 오염"],
    causes: ["식이 변경", "기생충", "감염·염증", "스트레스"],
    homeCare: [
      "탈수·식욕 관찰",
      "화장실을 더 자주 청소해 관찰 용이하게",
    ],
    seeVetWhen: [
      "혈변·구토 동반",
      "어린 고양이·지속 24~48시간",
    ],
    prevention: [
      "구충",
      "급격한 사료 변경 피하기",
      "위생·스트레스 관리",
    ],
    relatedSlugs: ["cat-panleukopenia", "cat-vomiting"],
  }),
  guide({
    slug: "cat-hcm",
    title: "비대성 심근병증(HCM)",
    species: ["cat"],
    kind: "disease",
    system: "heart",
    urgency: "emergency",
    summary:
      "심장 근육이 두꺼워지는 질환으로, 호흡곤란·마비(혈전)로 갑자기 드러나기도 합니다.",
    signals: [
      "호흡수 증가·개구호흡",
      "기력 저하·숨기",
      "뒷다리 마비·극심한 통증(혈전)",
      "실신",
    ],
    causes: ["유전적 소인", "일부 품종 고위험", "특발성"],
    homeCare: [
      "안정 시 호흡수 측정 습관",
      "호흡 이상 시 즉시 병원(무리한 보정 금지)",
    ],
    seeVetWhen: [
      "호흡곤란·마비 — 응급",
      "품종·잡음 시 심장초음파 상담",
    ],
    prevention: [
      "고위험 품종 스크리닝",
      "정기 검진·혈압",
      "비만·스트레스 관리",
    ],
    relatedSlugs: ["cat-breathing-emergency", "cat-senior-checkup"],
  }),
  guide({
    slug: "cat-conjunctivitis",
    title: "결막염",
    species: ["cat"],
    kind: "disease",
    system: "eye",
    urgency: "soon",
    summary:
      "눈곱·충혈·깜빡임이 특징입니다. 허피스 등 감염과 자주 동반됩니다.",
    signals: ["눈곱", "충혈", "빛을 꺼림", "한쪽 또는 양쪽"],
    causes: ["바이러스·세균", "자극·알러지", "이물"],
    homeCare: [
      "분비물을 미온수로 부드럽게",
      "사람 안약 금지",
    ],
    seeVetWhen: [
      "통증·각막 혼탁",
      "전신 감기 증상 동반",
    ],
    prevention: [
      "백신·스트레스 관리",
      "다묘 위생",
    ],
    relatedSlugs: ["cat-uri"],
  }),
  guide({
    slug: "cat-fleas-ticks",
    title: "벼룩·진드기",
    species: ["cat"],
    kind: "disease",
    system: "parasite",
    urgency: "soon",
    summary:
      "가려움·빈혈·알러지·매개질환의 원인입니다. 보이는 성충만 잡으면 재감염이 반복됩니다.",
    signals: [
      "가려움·검은 벼룩똥",
      "목·엉덩이 과잉 그루밍",
      "진드기 부착",
      "창백(빈혈)",
    ],
    causes: ["외부 기생충", "환경 오염", "예방 누락"],
    homeCare: [
      "수의사 추천 제품으로 동물+환경 동시 관리",
      "진드기는 올바르게 제거(비틀어 뽑지 않기)",
    ],
    seeVetWhen: [
      "대량 감염·빈혈",
      "피부 감염 이차화",
    ],
    prevention: [
      "연중 예방",
      "산책·이사·새 동물 합사 시 점검",
    ],
    relatedSlugs: ["cat-overgrooming", "cat-anemia"],
  }),
  guide({
    slug: "cat-constipation",
    title: "고양이 변비",
    species: ["cat"],
    kind: "symptom",
    system: "digestive",
    urgency: "soon",
    summary:
      "딱딱한 변·힘주기·화장실 잦은 방문이 나타납니다. 거대결장으로 만성화될 수 있습니다.",
    signals: [
      "며칠간 변 없음",
      "작은 딱딱한 변",
      "식욕 저하·구토",
    ],
    causes: [
      "탈수·통증(관절)",
      "이물·종양·신경 문제",
      "비만·활동 저하",
    ],
    homeCare: [
      "수분·습식 늘리기",
      "임의 관장 금지",
    ],
    seeVetWhen: [
      "48시간 이상 무변·구토",
      "반복 변비",
    ],
    prevention: [
      "수분·섬유(수의사 상담)",
      "화장실 접근성(낮고 넓게)",
      "체중·관절 관리",
    ],
    relatedSlugs: ["cat-flutd", "cat-obesity"],
  }),
  guide({
    slug: "cat-overgrooming",
    title: "과잉 그루밍(탈모)",
    species: ["cat"],
    kind: "symptom",
    system: "behavior",
    urgency: "soon",
    summary:
      "배를 비롯해 대칭성으로 털이 짧아지거나 벗겨지면 가려움·통증·스트레스를 의심합니다.",
    signals: [
      "국소 탈모",
      "과도한 핥기",
      "피부 발진",
    ],
    causes: [
      "벼룩·알러지·통증",
      "심리적 스트레스",
      "피부 감염",
    ],
    homeCare: [
      "벼룩 예방 먼저",
      "환경 풍부화·안정",
      "처벌하지 않기",
    ],
    seeVetWhen: [
      "피부 손상·감염",
      "원인 감별(내과·피부·행동)",
    ],
    prevention: [
      "기생충·알러지 관리",
      "다묘 자원 분배",
      "일관된 루틴",
    ],
    relatedSlugs: ["cat-fleas-ticks", "cat-stress-prevention"],
  }),
  guide({
    slug: "cat-fip",
    title: "복막염(FIP)",
    species: ["cat"],
    kind: "disease",
    system: "infectious",
    urgency: "emergency",
    summary:
      "코로나바이러스 변이로 발생하는 중증 질환입니다. 복수·호흡·신경 증상 등 형태가 다양합니다.",
    signals: [
      "발열·성장 부진",
      "복부 팽만(습성)",
      "눈·신경 증상(건성)",
      "극심한 무기력",
    ],
    causes: ["FCoV 변이", "밀집·스트레스·어린 개체"],
    homeCare: ["의심 시 전문 병원 상담", "임의 치료 금지"],
    seeVetWhen: ["지속 발열·복수·신경 증상"],
    prevention: [
      "위생·밀도 관리",
      "스트레스 감소",
      "새 고양이 검역",
    ],
    relatedSlugs: ["cat-uri", "cat-anemia"],
  }),
  guide({
    slug: "cat-anemia",
    title: "빈혈",
    species: ["cat"],
    kind: "symptom",
    system: "general",
    urgency: "soon",
    summary:
      "잇몸 창백·무기력·빠른 호흡이 나타날 수 있습니다. 원인(출혈·용혈·만성질환) 감별이 중요합니다.",
    signals: [
      "창백한 잇몸",
      "쉽게 지침",
      "식욕 저하",
      "빠른 호흡·심박",
    ],
    causes: [
      "벼룩·출혈",
      "감염·면역매개",
      "만성신부전 등",
    ],
    homeCare: ["원인 치료 전 철분 임의 투여 금지"],
    seeVetWhen: ["창백·기력 저하 — 당일 진료"],
    prevention: [
      "기생충 예방",
      "독성 물질(양파 등) 차단",
      "만성질환 정기 검진",
    ],
    relatedSlugs: ["cat-ckd", "cat-fleas-ticks"],
  }),
  guide({
    slug: "cat-ringworm",
    title: "곰팡이 피부병(링웜)",
    species: ["cat"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "원형 탈모·비늘이 특징이며 사람에게도 옮을 수 있습니다. 어린 고양이·밀집 환경에서 흔합니다.",
    signals: [
      "동그란 탈모 반점",
      "비듬·가려움(개인차)",
      "발톱 주변 병변",
    ],
    causes: ["피부사상균", "면역 저하·밀집"],
    homeCare: [
      "격리·환경 청소(수의사 지침)",
      "사람 접촉 위생",
    ],
    seeVetWhen: [
      "탈모 반점",
      "다묘 가정 전파",
    ],
    prevention: [
      "새 고양이 검역",
      "스트레스·영양 관리",
      "위생",
    ],
    relatedSlugs: ["cat-overgrooming"],
  }),
  guide({
    slug: "cat-breathing-emergency",
    title: "고양이 숨 가쁠 때 응급",
    species: ["cat"],
    kind: "prevention",
    system: "respiratory",
    urgency: "emergency",
    summary:
      "개구호흡·복부 호흡·숨기 행동은 응급 신호일 수 있습니다. 보정·이동 시 스트레스를 최소화하세요.",
    signals: [
      "입을 벌리고 헐떡임",
      "팔꿈치 벌린 자세",
      "청색·창백한 잇몸",
      "극도로 숨음",
    ],
    causes: ["심장·폐·천식·통증·열사병 등"],
    homeCare: [
      "시원하고 조용한 공간",
      "억지로 잡거나 약 먹이기 금지",
      "즉시 병원 이동",
    ],
    seeVetWhen: ["위 신호 중 하나라도 — 응급"],
    prevention: [
      "안정 시 호흡수 기록(대개 <30/분 참고)",
      "심장·천식 위험묘 정기 검진",
      "고온 환경 피하기",
    ],
    relatedSlugs: ["cat-hcm", "cat-uri"],
  }),
  guide({
    slug: "cat-excessive-meowing",
    title: "고양이가 과하게 우는 이유",
    species: ["cat"],
    kind: "symptom",
    system: "behavior",
    urgency: "monitor",
    summary:
      "요구·불안·통증·인지장애·갑상선항진 등 원인이 섞입니다. 패턴 변화가 핵심입니다.",
    signals: [
      "밤중 울음",
      "갑자기 음성이 커짐",
      "따라다니며 울음",
    ],
    causes: [
      "관심 요구·분리불안",
      "통증·고혈압·갑상선",
      "노령 인지 변화",
    ],
    homeCare: [
      "낮 놀이·야간 루틴",
      "새벽 울음에 즉시 보상하지 않기",
      "환경 Enrichment",
    ],
    seeVetWhen: [
      "노령묘의 갑작스러운 야간 울음",
      "다른 신체 증상 동반",
    ],
    prevention: [
      "규칙적 놀이",
      "시니어 검진",
      "스트레스 최소화",
    ],
    relatedSlugs: ["cat-hyperthyroidism", "cat-senior-checkup", "cat-stress-prevention"],
  }),
  guide({
    slug: "cat-vaccination",
    title: "고양이 예방접종 가이드",
    species: ["cat"],
    kind: "prevention",
    system: "infectious",
    urgency: "monitor",
    summary:
      "핵심 백신과 라이프스타일(실내/외출)에 따른 추가 접종을 정리합니다.",
    signals: ["접종 시기", "입양·합사 전"],
    causes: ["전염병 노출 위험"],
    homeCare: ["접종 기록 관리", "접종 후 관찰"],
    seeVetWhen: ["알레르기 반응", "일정 공백"],
    prevention: [
      "핵심 백신 유지",
      "신규 고양이 검역",
      "위생·밀도 관리",
    ],
    relatedSlugs: ["cat-panleukopenia", "cat-uri"],
  }),
  guide({
    slug: "cat-senior-checkup",
    title: "고양이 건강검진 주기",
    species: ["cat"],
    kind: "prevention",
    system: "general",
    urgency: "monitor",
    summary:
      "고양이는 아픔을 숨깁니다. 연령별 혈액·소변·혈압·구강·체중 체크리스트입니다.",
    signals: [
      "물·소변·체중 변화",
      "그루밍 감소",
      "점프 감소",
      "숨는 시간 증가",
    ],
    causes: ["만성질환 조기 발견 필요"],
    homeCare: [
      "월 체중 기록",
      "안정 시 호흡수",
    ],
    seeVetWhen: [
      "성묘 연 1회, 시니어 연 2회 권장(개별화)",
      "이상 신호 즉시",
    ],
    prevention: [
      "치과·신장·갑상선·혈압 중심 관리",
      "비만 예방",
      "스트레스 관리",
    ],
    relatedSlugs: ["cat-ckd", "cat-hyperthyroidism", "cat-hcm"],
  }),
  guide({
    slug: "cat-stress-prevention",
    title: "고양이 스트레스·환경 케어",
    species: ["cat"],
    kind: "prevention",
    system: "behavior",
    urgency: "monitor",
    summary:
      "FLUTD·과잉그루밍·울음의 상당수가 스트레스와 연결됩니다. 자원·수직공간·루틴이 예방의 핵심입니다.",
    signals: [
      "화장실 실수",
      "숨기·공격성",
      "과잉 그루밍",
    ],
    causes: ["환경 변화", "다묘 갈등", "예측 불가능성"],
    homeCare: [
      "화장실·식기·스크래처 충분히",
      "높은 도망 루트",
      "일정 시간 사냥 놀이",
    ],
    seeVetWhen: [
      "신체 질환 배제가 필요할 때",
      "심한 행동 문제",
    ],
    prevention: [
      "변화는 천천히",
      "합사는 단계적으로",
      "일관된 하루 리듬",
    ],
    relatedSlugs: ["cat-flutd", "cat-overgrooming", "cat-excessive-meowing"],
  }),
];
