import { guide } from "@/lib/health/guide";
import type { HealthGuide } from "@/lib/health/types";

/** 강아지 질병·증상·예방 가이드 */
export const DOG_GUIDES: HealthGuide[] = [
  guide({
    slug: "dog-patellar-luxation",
    title: "슬개골 탈구",
    species: ["dog"],
    kind: "disease",
    system: "joint",
    urgency: "soon",
    summary:
      "무릎뼈(슬개골)가 정상 위치에서 빠져 절뚝거림·토끼뛰기 걸음이 나타나는 질환입니다. 소형견에서 특히 흔하며, 등급에 따라 관리·수술이 달라집니다.",
    signals: [
      "뒷다리를 잠깐 들고 걷거나 토끼처럼 뛰는 걸음",
      "앉을 때 한쪽 다리를 펴지 못함",
      "산책 후 통증·기력 저하",
      "무릎에서 ‘딱’ 하는 느낌(보호자 체감)",
    ],
    causes: [
      "선천적 대퇴골·경골 구조 이상",
      "급성장·과체중으로 관절 부담 증가",
      "외상성 탈구(낙상·점프)",
    ],
    homeCare: [
      "미끄러운 바닥은 러그·양말로 미끄럼을 줄이세요",
      "소파·침대 점프를 막고 낮은 계단·발판을 제공하세요",
      "체중을 이상 체형으로 유지하는 것이 통증 조절의 핵심입니다",
    ],
    seeVetWhen: [
      "절뚝임이 반복되거나 하루 이상 지속",
      "만지면 아파하거나 만지는 것을 피함",
      "수술 여부·재활이 필요한 등급인지 평가가 필요할 때",
    ],
    prevention: [
      "성장기 과한 점프·장시간 격렬 운동 조절",
      "슬개골 취약 견종은 정기 정형외과 검진",
      "관절 영양은 수의사 상담 후 선택",
    ],
    relatedSlugs: ["dog-limping", "dog-arthritis", "dog-obesity"],
  }),
  guide({
    slug: "dog-otitis",
    title: "외이염",
    species: ["dog"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "귓바퀴·외이도의 염증으로 가려움·냄새·분비물이 생깁니다. 알러지·습도·이물·기생충이 흔히 겹칩니다.",
    signals: [
      "귀를 긁거나 바닥에 비빔",
      "고약한 냄새·갈색/노란색 분비물",
      "귀 주변 발적·부종",
      "머리 기울임·통증 반응",
    ],
    causes: [
      "알러지(음식·환경)",
      "효모·세균 감염",
      "귀진드기",
      "습기·통풍 부족(처진 귀)",
    ],
    homeCare: [
      "수의사가 처방한 세정제·약만 사용하세요(임의 면봉 깊게 금지)",
      "목욕 후 귀를 가볍게 건조",
      "재발이 잦으면 알러지 원인을 함께 점검",
    ],
    seeVetWhen: [
      "통증·부종·출혈이 심할 때",
      "머리 기울임·균형 이상(중이 침범 가능)",
      "2주 이상 반복되는 만성 외이염",
    ],
    prevention: [
      "수영·목욕 후 귀 관리 루틴",
      "알러지 관리·식이 점검",
      "정기 귀 상태 관찰",
    ],
    relatedSlugs: ["dog-allergy", "dog-atopy"],
  }),
  guide({
    slug: "dog-atopy",
    title: "아토피 피부염",
    species: ["dog"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "환경 알러젠에 대한 만성 가려움 질환입니다. 발·겨드랑이·사타구니·얼굴을 집중적으로 긁는 패턴이 전형적입니다.",
    signals: [
      "발바닥·발가락 사이 핥기",
      "겨드랑이·사타구니 발적",
      "계절성으로 심해지는 가려움",
      "이차 감염으로 냄새·딱지",
    ],
    causes: [
      "집먼지진드기·꽃가루·곰팡이 등 환경 알러젠",
      "피부 장벽 약화",
      "유전적 소인",
    ],
    homeCare: [
      "처방 약·샴푸·보습 스케줄을 지키세요",
      "발 핥기 방지를 위해 산책 후 발 닦기",
      "실내 먼지·침구 청결 관리",
    ],
    seeVetWhen: [
      "가려움으로 수면·식사를 방해할 때",
      "피부 감염 징후(고름·심한 냄새)",
      "음식 알러지와 감별이 필요할 때",
    ],
    prevention: [
      "피부 장벽 관리(보습·적절한 목욕 간격)",
      "알러지 시즌 전 예방적 상담",
      "체중·스트레스 관리",
    ],
    relatedSlugs: ["dog-allergy", "dog-otitis"],
  }),
  guide({
    slug: "dog-parvo",
    title: "파보 장염",
    species: ["dog"],
    kind: "disease",
    system: "infectious",
    urgency: "emergency",
    summary:
      "파보바이러스에 의한 급성 장염으로, 어린 강아지에서 특히 치명적일 수 있습니다. 구토·혈변·탈수가 빠르게 진행됩니다.",
    signals: [
      "갑작스러운 구토·식욕 소실",
      "심한 설사·혈변(냄새가 독함)",
      "무기력·탈수",
      "발열 또는 체온 저하",
    ],
    causes: ["개 파보바이러스(CPV) 감염", "예방접종 미완료·불완전", "오염된 환경 노출"],
    homeCare: [
      "가정 처치로 해결하려 하지 마세요 — 즉시 병원",
      "다른 강아지와 격리, 분비물 소독",
      "수액·항구토·영양 지원은 병원 처치가 핵심",
    ],
    seeVetWhen: ["의심 증상만으로도 즉시 응급 진료", "어린 강아지·미접종견은 더 긴급"],
    prevention: [
      "기본 예방접종 스케줄 준수",
      "접종 완료 전 공원·애견카페 노출 최소화",
      "보호소·펫샵 입양 직후 검역·검진",
    ],
    relatedSlugs: ["dog-vomiting", "dog-diarrhea", "dog-vaccination-schedule"],
  }),
  guide({
    slug: "dog-kennel-cough",
    title: "켄넬코프",
    species: ["dog"],
    kind: "disease",
    system: "respiratory",
    urgency: "soon",
    summary:
      "전염성 기관지염으로 ‘거위 울음’ 같은 마른기침이 특징입니다. 대부분 경증이지만 어린·노령·기저질환견은 악화될 수 있습니다.",
    signals: [
      "거위 소리 같은 기침",
      "목에 이물감처럼 헛구역질",
      "콧물·미열",
      "활동은 비교적 유지되는 경우도 많음",
    ],
    causes: [
      "보르데텔라·파라인플루엔자 등 복합 병원체",
      "밀집 환경(호텔·유치원·보호소)",
    ],
    homeCare: [
      "충분히 쉬게 하고 목줄을 하네스로 바꿔 기관 자극을 줄이세요",
      "가습·환기로 호흡기 자극을 완화",
      "다른 강아지와의 접촉을 일시 중단",
    ],
    seeVetWhen: [
      "호흡곤란·청색증·고열",
      "식욕·기력이 급격히 떨어질 때",
      "어린 강아지·노령견·심장질환견",
    ],
    prevention: [
      "밀집 시설 이용 전 수의사와 백신·예방 상담",
      "아픈 개와의 접촉 피하기",
      "스트레스·환기 불량 환경 개선",
    ],
    relatedSlugs: ["dog-cough", "dog-vaccination-schedule"],
  }),
  guide({
    slug: "dog-heartworm",
    title: "심장사상충",
    species: ["dog"],
    kind: "disease",
    system: "parasite",
    urgency: "soon",
    summary:
      "모기가 옮기는 기생충이 심장·폐혈관에 기생합니다. 예방이 치료보다 훨씬 안전하고 쉽습니다.",
    signals: [
      "만성 기침·운동 시 쉽게 지침",
      "호흡수 증가",
      "복수가 차는 심한 경우",
      "초기에는 증상이 거의 없을 수 있음",
    ],
    causes: ["모기에 의한 유충 전파", "예방약 누락·불규칙 투약"],
    homeCare: [
      "임의 구충제 고용량 투약은 위험 — 반드시 수의사 프로토콜",
      "확진 후 활동 제한 등 지시 준수",
    ],
    seeVetWhen: [
      "예방약 시작 전 감염 여부 검사",
      "기침·운동불내성이 있을 때",
      "예방을 수개월 이상 중단했을 때",
    ],
    prevention: [
      "월 1회(또는 수의사 권장 주기) 예방약",
      "연 1회 이상 항원 검사",
      "모기 시즌뿐 아니라 연중 예방이 권장되는 지역이 많음",
    ],
    relatedSlugs: ["dog-cough", "dog-parasite-prevention"],
  }),
  guide({
    slug: "dog-periodontal",
    title: "치주질환",
    species: ["dog"],
    kind: "disease",
    system: "dental",
    urgency: "soon",
    summary:
      "치석·치은염에서 시작해 잇몸·치조골이 손상되는 질환입니다. 통증뿐 아니라 전신 염증 부담과도 연관됩니다.",
    signals: [
      "입 냄새",
      "잇몸 출혈·발적",
      "단단한 간식을 피함·한쪽으로만 씹음",
      "치석이 눈에 띔",
    ],
    causes: ["치태 축적", "소형견·부정교합", "양치·덴탈케어 부족"],
    homeCare: [
      "매일 또는 주 수회 양치(펫용 치약)",
      "수의사 추천 덴탈껌·워터첨가제 보조",
      "스케일링은 전신마취 하 전문 처치가 표준",
    ],
    seeVetWhen: [
      "심한 구취·통증·식욕 저하",
      "얼굴 부종·코피(치근단 농양 가능)",
      "정기 구강 검진·스케일링 상담",
    ],
    prevention: [
      "어린 시기부터 양치 훈련",
      "연 1회 구강 검진",
      "간식은 ‘치아에 달라붙는’ 종류를 줄이기",
    ],
    relatedSlugs: ["dog-senior-checkup"],
  }),
  guide({
    slug: "dog-vomiting",
    title: "강아지 구토",
    species: ["dog"],
    kind: "symptom",
    system: "digestive",
    urgency: "soon",
    summary:
      "구토는 단순 식이 실수부터 이물·췌장염·감염·전신질환까지 원인이 다양합니다. ‘몇 번이냐·무엇이 나오느냐·전신 상태’로 긴급도를 가늠합니다.",
    signals: [
      "토한 뒤에도 다시 먹으려 함 vs 완전히 거부",
      "황색 담즙·음식물·혈액·이물",
      "동반 설사·무기력·복통",
    ],
    causes: [
      "급하게 먹음·식이 변경·쓰레기 섭취",
      "이물·중독",
      "감염·췌장염·신장·간·내분비 질환",
    ],
    homeCare: [
      "가벼운 1회성·활력 정상이면 짧은 절식 후 자극 적은 식이(수의사 지침)",
      "사람약(진토제 등) 임의 복용 금지",
      "토사물 사진·시간을 기록",
    ],
    seeVetWhen: [
      "반복 구토·혈토·이물 의심",
      "어린 강아지·노령견",
      "무기력·탈수·복통·발열",
      "중독·파보 가능 환경",
    ],
    prevention: [
      "급식 속도 조절·식이 급변 피하기",
      "쓰레기·독성 음식 차단",
      "정기 기생충·백신 관리",
    ],
    relatedSlugs: ["dog-diarrhea", "dog-pancreatitis", "dog-parvo"],
  }),
  guide({
    slug: "dog-diarrhea",
    title: "강아지 설사",
    species: ["dog"],
    kind: "symptom",
    system: "digestive",
    urgency: "soon",
    summary:
      "급성은 식이·스트레스·감염이 흔하고, 만성은 염증성장·알러지·기생충 등을 의심합니다. 혈변·탈수는 병원 신호입니다.",
    signals: [
      "무른 변~물설사",
      "점액·혈변",
      "잦은 배변·힘주기",
      "식욕·기력 변화",
    ],
    causes: [
      "식이 변경·과식·상한 음식",
      "기생충·바이러스·세균",
      "췌장·간·장 염증성 질환",
    ],
    homeCare: [
      "탈수 여부를 잇몸·피부탄력으로 관찰",
      "임의 지사제·사람약 금지",
      "변 사진·빈도 기록",
    ],
    seeVetWhen: [
      "혈변·검은변·반복 구토 동반",
      "24시간 이상 지속(어린 개체는 더 빨리)",
      "탈수·고열·극심한 무기력",
    ],
    prevention: [
      "사료 급변 시 7일에 걸쳐 혼합",
      "구충·위생",
      "식탁 음식 공유 최소화",
    ],
    relatedSlugs: ["dog-vomiting", "dog-parvo", "dog-pancreatitis"],
  }),
  guide({
    slug: "dog-cough",
    title: "강아지 기침",
    species: ["dog"],
    kind: "symptom",
    system: "respiratory",
    urgency: "soon",
    summary:
      "켄넬코프뿐 아니라 기관허탈·심장병·폐질환·이물도 기침으로 나타납니다. 야간·운동 후·흥분 시 패턴을 기록하세요.",
    signals: [
      "마른기침 vs 가래 기침",
      "거위 울음 소리",
      "운동 후·밤에 심해짐",
      "호흡수·잇몸색 변화",
    ],
    causes: [
      "감염성 기관지염",
      "기관 허탈(소형견)",
      "심장사상충·판막질환",
      "알레르기·이물",
    ],
    homeCare: [
      "목줄 대신 하네스",
      "연기·미세먼지 노출 줄이기",
      "호흡수(안정 시)를 기록",
    ],
    seeVetWhen: [
      "호흡곤란·청색 잇몸",
      "실신·극심한 무기력",
      "2~3일 이상 지속되거나 악화",
    ],
    prevention: [
      "밀집 시설 전 건강 체크",
      "심장사상충 예방",
      "비만 관리(호흡 부담↓)",
    ],
    relatedSlugs: ["dog-kennel-cough", "dog-heartworm"],
  }),
  guide({
    slug: "dog-cataract",
    title: "백내장",
    species: ["dog"],
    kind: "disease",
    system: "eye",
    urgency: "soon",
    summary:
      "수정체가 혼탁해져 시력이 떨어지는 질환입니다. 노령·당뇨·유전과 연관되며, ‘핵경화’와 감별이 필요합니다.",
    signals: [
      "동공이 희뿌옇게 보임",
      "밤에 더듬거리거나 부딪힘",
      "점프·계단을 꺼림",
    ],
    causes: ["노화", "당뇨", "유전", "외상·염증 후유"],
    homeCare: [
      "가구 배치를 급히 바꾸지 않기",
      "밤에도 약한 조명으로 길 안내",
      "당뇨견은 혈당·정기 안과 검진",
    ],
    seeVetWhen: [
      "급격한 시력 저하·통증·충혈",
      "수술 가능 여부 평가가 필요할 때",
      "당뇨와 동반될 때",
    ],
    prevention: [
      "정기 안과·전신 검진",
      "당뇨 관리",
      "눈 외상 예방",
    ],
    relatedSlugs: ["dog-senior-checkup", "dog-diabetes-prevention"],
  }),
  guide({
    slug: "dog-arthritis",
    title: "관절염",
    species: ["dog"],
    kind: "disease",
    system: "joint",
    urgency: "monitor",
    summary:
      "연골·관절 염증으로 통증과 가동 범위 감소가 생깁니다. 노령·대형견·과체중에서 흔하며 조기 관리가 삶의 질을 바꿉니다.",
    signals: [
      "일어나기 힘들어함",
      "산책 거리 단축·절뚝임",
      "날씨 변화에 통증 악화",
      "만지면 예민",
    ],
    causes: [
      "노화·퇴행",
      "십자인대·고관절·슬개골 질환 후유",
      "비만·과도한 충격 운동",
    ],
    homeCare: [
      "짧은 산책을 여러 번",
      "미끄럼 방지·경사로",
      "체중 감량이 진통보다 먼저인 경우도 많음",
    ],
    seeVetWhen: [
      "통증으로 공격성·식욕 저하",
      "갑자기 한쪽 다리를 전혀 못 쓸 때",
      "약물·물리치료·주사 옵션 상담",
    ],
    prevention: [
      "적정 체중",
      "성장기 과한 충격 운동 조절",
      "정기 정형외과 체크",
    ],
    relatedSlugs: ["dog-patellar-luxation", "dog-limping", "dog-obesity"],
  }),
  guide({
    slug: "dog-pancreatitis",
    title: "췌장염",
    species: ["dog"],
    kind: "disease",
    system: "digestive",
    urgency: "emergency",
    summary:
      "췌장 염증으로 구토·복통·식욕부진이 급격히 나타날 수 있습니다. 고지방 식사 후 급성으로 오는 경우가 많습니다.",
    signals: [
      "반복 구토",
      "그루밍하듯 웅크리거나 복통 자세",
      "극심한 식욕 소실",
      "설사·발열·탈수",
    ],
    causes: [
      "고지방 음식(사람 음식·잔반)",
      "비만·내분비 질환",
      "일부 약물·유전적 소인",
    ],
    homeCare: [
      "가정에서 금식만으로 버티지 말고 진료",
      "회복기에는 처방 저지방 식이만",
    ],
    seeVetWhen: ["의심되면 당일 진료", "쇼크·지속 구토·혈변"],
    prevention: [
      "식탁 음식·지방 간식 차단",
      "명절·외식 사고 예방",
      "비만 관리",
    ],
    relatedSlugs: ["dog-vomiting", "dog-diarrhea", "dog-obesity"],
  }),
  guide({
    slug: "dog-cystitis-urolith",
    title: "방광염·요로결석",
    species: ["dog"],
    kind: "disease",
    system: "urinary",
    urgency: "soon",
    summary:
      "배뇨 통증·잦은 배뇨·혈뇨가 나타나면 방광염이나 결석을 의심합니다. 수컷의 요도폐색은 응급입니다.",
    signals: [
      "자주 조금 싸거나 힘주기",
      "혈뇨·탁한 소변",
      "배뇨 시 울음·통증",
      "소변을 전혀 못 보는 경우(응급)",
    ],
    causes: [
      "세균 감염",
      "결석·결정",
      "물 섭취 부족·배뇨 참기",
    ],
    homeCare: [
      "신선한 물 접근성을 높이세요",
      "배뇨 간격이 너무 길어지지 않게",
      "임의 이뇨·민간요법 금지",
    ],
    seeVetWhen: [
      "무뇨·극심한 통증·구토",
      "혈뇨가 반복될 때",
      "재발이 잦아 결석 분석이 필요할 때",
    ],
    prevention: [
      "충분한 수분",
      "수의사 권장 처방식(결석 유형별)",
      "정기 소변검사",
    ],
    relatedSlugs: ["dog-senior-checkup"],
  }),
  guide({
    slug: "dog-cushing",
    title: "쿠싱증후군",
    species: ["dog"],
    kind: "disease",
    system: "endocrine",
    urgency: "soon",
    summary:
      "코르티솔 과다로 갈증·다뇨·식욕 증가·배 팽만·피부 변화가 나타납니다. 중년 이후에서 흔히 진단됩니다.",
    signals: [
      "물을 많이 마시고 소변을 자주/많이 봄",
      "배가 나오고 근육이 빠짐",
      "양쪽 대칭성 탈모·얇은 피부",
      "헐떡임 증가",
    ],
    causes: [
      "뇌하수체·부신 종양/과형성",
      "장기 스테로이드 투약(의인성)",
    ],
    homeCare: [
      "물·배변 패턴을 기록해 병원에 제공",
      "피부 감염·요로감염 2차 문제에 주의",
    ],
    seeVetWhen: [
      "다갈다뇨가 지속될 때",
      "확진 검사(ACTH·LDDST 등) 상담",
      "치료 중 부작용 모니터링",
    ],
    prevention: [
      "스테로이드 장기 사용은 수의사 감독 하에서만",
      "중년 이후 정기 혈액·소변 검진",
    ],
    relatedSlugs: ["dog-senior-checkup"],
  }),
  guide({
    slug: "dog-seizure",
    title: "발작·간질",
    species: ["dog"],
    kind: "disease",
    system: "neuro",
    urgency: "emergency",
    summary:
      "의식 변화와 경련이 반복되면 특발성 간질이나 대사·독성·뇌질환을 감별해야 합니다. 발작 중 안전이 최우선입니다.",
    signals: [
      "쓰러짐·다리 젓기·침 흘림",
      "발작 전 불안·시선 고정",
      "발작 후 혼란·실명처럼 보임(일시)",
      "5분 이상 지속되는 경련(응급)",
    ],
    causes: [
      "특발성 간질",
      "저혈당·간부전·독성",
      "뇌염·종양·외상",
    ],
    homeCare: [
      "주변에 위험한 물건을 치우고 억지로 입을 벌리지 마세요",
      "시작·종료 시각을 영상으로 기록",
      "연속 발작·긴 발작은 즉시 병원",
    ],
    seeVetWhen: [
      "첫 발작",
      "5분 이상·연속 발작",
      "어린 강아지·독성 의심",
    ],
    prevention: [
      "독성 물질·사람약 보관",
      "처방 항경련제 규칙 투약",
      "유발 스트레스·수면 부족 관리",
    ],
    relatedSlugs: ["dog-seizure-first-aid"],
  }),
  guide({
    slug: "dog-ivdd",
    title: "디스크(추간판탈출)",
    species: ["dog"],
    kind: "disease",
    system: "joint",
    urgency: "emergency",
    summary:
      "척추 디스크 물질이 신경을 압박해 통증·마비·배뇨장애를 일으킵니다. 코기·닥스 등에서 특히 주의합니다.",
    signals: [
      "등을 굽히고 떨림·비명",
      "뒷다리 힘 빠짐·드래깅",
      "배뇨·배변 장애",
      "점프·계단 거부",
    ],
    causes: [
      "연골이영양증 견종 소인",
      "점프·급격한 동작",
      "비만",
    ],
    homeCare: [
      "의심 시 즉시 안정(케이지 리스팅) 및 병원",
      "목줄 당김·계단 금지",
    ],
    seeVetWhen: [
      "마비·심한 통증·배뇨 불가 — 응급",
      "영상(MRI/CT) 평가가 필요할 때",
    ],
    prevention: [
      "소파 점프 방지·경사로",
      "체중 관리",
      "하네스 사용",
    ],
    relatedSlugs: ["dog-limping", "dog-arthritis"],
  }),
  guide({
    slug: "dog-tear-stains",
    title: "눈물자국",
    species: ["dog"],
    kind: "symptom",
    system: "eye",
    urgency: "monitor",
    summary:
      "눈물 과다·색소 침착으로 눈 아래가 갈색으로 물드는 현상입니다. 미용 문제일 수도, 안과·피부·치아 원인이 있을 수도 있습니다.",
    signals: [
      "내안각 아래 갈색 착색",
      "눈물 고임·눈곱",
      "가려워 비빔",
    ],
    causes: [
      "눈물길 협착·내안각 피모",
      "알러지·자극",
      "치아·안면 구조",
    ],
    homeCare: [
      "눈 주위를 부드럽게 세정(안과용)",
      "얼굴을 핥는 습관·오염 관리",
      "표백 민간요법·사람 화장품 금지",
    ],
    seeVetWhen: [
      "충혈·통증·시력 이상",
      "심한 냄새·피부염",
      "갑자기 눈물이 늘 때",
    ],
    prevention: [
      "얼굴 피모 정리(전문가)",
      "알러지·식이 점검",
      "정기 안과 체크",
    ],
    relatedSlugs: ["dog-allergy", "dog-atopy"],
  }),
  guide({
    slug: "dog-obesity",
    title: "비만",
    species: ["dog"],
    kind: "disease",
    system: "metabolic",
    urgency: "monitor",
    summary:
      "과체중은 관절·호흡·당뇨·수명에 영향을 줍니다. ‘통통함이 귀여움’보다 갈비뼈 촉지·허리 라인이 기준입니다.",
    signals: [
      "위에서 볼 때 허리가 사라짐",
      "갈비뼈가 잘 안 만져짐",
      "조금만 걸어도 헐떡임",
      "그루밍·움직임 감소",
    ],
    causes: [
      "과잉 칼로리·간식",
      "운동 부족",
      "중성화 후 대사 저하",
      "내분비 질환(일부)",
    ],
    homeCare: [
      "간식 칼로리를 일일 열량의 10% 이내로",
      "계량컵으로 사료 고정",
      "짧은 산책 빈도 증가",
    ],
    seeVetWhen: [
      "급격한 체중 증가/감소",
      "감량 처방·갑상선 등 감별이 필요할 때",
    ],
    prevention: [
      "중성화 후 급여량 재조정",
      "가족 모두 같은 급식 규칙",
      "정기 체중 기록",
    ],
    relatedSlugs: ["dog-arthritis", "dog-pancreatitis", "dog-diabetes-prevention"],
  }),
  guide({
    slug: "dog-allergy",
    title: "알러지",
    species: ["dog"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "음식·환경·벼룩 알러지가 가려움·외이염·위장 증상으로 나타납니다. ‘알러지 간식’보다 원인 감별이 우선입니다.",
    signals: [
      "발·귀·사타구니 가려움",
      "계절성 또는 연중 증상",
      "만성 외이염",
      "설사·구토가 동반되기도 함",
    ],
    causes: [
      "환경 알러젠",
      "음식 단백질",
      "벼룩 타액",
    ],
    homeCare: [
      "벼룩 예방을 최우선으로",
      "식이 제거/유발 시험은 수의사 프로토콜로",
      "가려움으로 피부를 못 뜯게 보호",
    ],
    seeVetWhen: [
      "수면·일상을 방해하는 가려움",
      "감염·외이염 반복",
      "아나필락시스 의심(부종·호흡곤란)",
    ],
    prevention: [
      "연중 외부기생충 예방",
      "급격한 식이 변경 피하기",
      "피부 보습·환경 청결",
    ],
    relatedSlugs: ["dog-atopy", "dog-otitis"],
  }),
  guide({
    slug: "dog-limping",
    title: "강아지 절뚝거림",
    species: ["dog"],
    kind: "symptom",
    system: "joint",
    urgency: "soon",
    summary:
      "앞다리·뒷다리에 따라 의심 질환이 달라집니다. 외상·슬개골·십자인대·디스크·이물까지 폭넓게 봅니다.",
    signals: [
      "무게를 못 싣거나 짧게 디딤",
      "특정 동작에서만 통증",
      "부종·열감",
    ],
    causes: [
      "염좌·골절·발바닥 이물",
      "슬개골·십자인대·고관절",
      "디스크·관절염",
    ],
    homeCare: [
      "무리한 산책·점프 중단",
      "발바닥·발톱·이물 확인",
      "24시간 지켜보기만 하지 말고 악화 시 즉시",
    ],
    seeVetWhen: [
      "전혀 디디지 못함",
      "비명·부종·변형",
      "마비·배뇨 이상 동반",
    ],
    prevention: [
      "미끄럼 방지",
      "적정 체중",
      "급격한 고강도 운동 조절",
    ],
    relatedSlugs: ["dog-patellar-luxation", "dog-ivdd", "dog-arthritis"],
  }),
  guide({
    slug: "dog-seizure-first-aid",
    title: "발작 응급처치",
    species: ["dog"],
    kind: "prevention",
    system: "neuro",
    urgency: "emergency",
    summary:
      "발작이 왔을 때 보호자가 해야 할 순서와 절대 하지 말아야 할 것을 정리한 응급 가이드입니다.",
    signals: ["경련 시작", "의식 소실", "침·배변실금"],
    causes: ["간질·독성·대사이상 등(원인 감별은 병원)"],
    homeCare: [
      "주변 안전 확보, 어두운 조용한 환경",
      "시간 측정·영상 기록",
      "입안에 손·물건 넣지 않기",
      "물·약을 억지로 먹이지 않기",
    ],
    seeVetWhen: [
      "첫 발작·5분 이상·연속 발작",
      "외상이 의심될 때",
      "독성 물질 노출 가능",
    ],
    prevention: [
      "처방약 시간 엄수",
      "독성 음식·약 차단",
      "발작 일기 작성",
    ],
    relatedSlugs: ["dog-seizure"],
  }),
  guide({
    slug: "dog-vaccination-schedule",
    title: "예방접종·스케줄 가이드",
    species: ["dog"],
    kind: "prevention",
    system: "infectious",
    urgency: "monitor",
    summary:
      "핵심 백신과 생활환경에 따른 추가 백신, 구충·심장사상충을 한 흐름으로 보는 예방 가이드입니다.",
    signals: ["접종 시기 도래", "시설 이용 예정", "입양 직후"],
    causes: ["전염병·기생충 노출 위험"],
    homeCare: [
      "접종 수첩·앱으로 일정을 관리",
      "접종 후 24시간 과격 운동·목욕 조절(수의사 지침)",
    ],
    seeVetWhen: [
      "접종 후 얼굴 부종·호흡곤란",
      "일정 누락 시 재시작 상담",
    ],
    prevention: [
      "기본 백신 + 지역/라이프스타일 맞춤",
      "심장사상충·외부기생충 연중 관리",
      "미접종 기간 고위험 장소 피하기",
    ],
    relatedSlugs: ["dog-parvo", "dog-kennel-cough", "dog-heartworm"],
  }),
  guide({
    slug: "dog-parasite-prevention",
    title: "기생충 예방 체크리스트",
    species: ["dog"],
    kind: "prevention",
    system: "parasite",
    urgency: "monitor",
    summary:
      "심장사상충·장내 기생충·벼룩·진드기를 월간 루틴으로 묶어 관리하는 예방 가이드입니다.",
    signals: ["가려움", "항문 비빔", "기침", "진드기 발견"],
    causes: ["모기·벼룩·진드기·분변 경구 감염"],
    homeCare: [
      "제품 체중·주기를 지켜 투약",
      "환경(침구·카펫) 동시 관리",
    ],
    seeVetWhen: [
      "대량 진드기·빈혈 의심",
      "예방약 부작용·구토 반복",
    ],
    prevention: [
      "연중 예방 습관화",
      "산책 후 몸 검사",
      "정기 분변·항원 검사",
    ],
    relatedSlugs: ["dog-heartworm", "dog-allergy"],
  }),
  guide({
    slug: "dog-senior-checkup",
    title: "노령견 건강검진 체크리스트",
    species: ["dog"],
    kind: "prevention",
    system: "general",
    urgency: "monitor",
    summary:
      "7세 전후부터 암·신장·심장·관절 위험이 올라갑니다. 연령별 권장 검사와 집에서 볼 신호를 정리했습니다.",
    signals: [
      "물·소변량 변화",
      "체중·식욕 변화",
      "기침·운동불내성",
      "행동·수면 변화",
    ],
    causes: ["노화에 따른 만성질환 증가"],
    homeCare: [
      "월 1회 체중·체형 점수 기록",
      "안정 시 호흡수 측정 습관",
    ],
    seeVetWhen: [
      "연 1~2회 시니어 패널(혈액·소변±영상)",
      "급격한 변화 시 즉시",
    ],
    prevention: [
      "치아·관절·체중 관리",
      "백신·기생충 유지",
      "환경 Enrichment로 인지 자극",
    ],
    relatedSlugs: ["dog-cataract", "dog-arthritis", "dog-cushing"],
  }),
  guide({
    slug: "dog-diabetes-prevention",
    title: "당뇨 위험 관리(강아지)",
    species: ["dog"],
    kind: "prevention",
    system: "endocrine",
    urgency: "monitor",
    summary:
      "다갈다뇨·체중 감소가 있으면 당뇨를 의심합니다. 비만·췌장염 병력견은 특히 관리가 중요합니다.",
    signals: ["물을 많이 마심", "소변량 증가", "식욕 있는데 체중 감소"],
    causes: ["인슐린 부족/저항", "비만", "일부 내분비·췌장 질환"],
    homeCare: [
      "규칙적 식사·간식 통제",
      "체중 감량 목표를 수의사와 설정",
    ],
    seeVetWhen: [
      "다갈다뇨",
      "기력 저하·구토(케톤산증 가능)",
    ],
    prevention: [
      "비만 예방",
      "고지방 사고 예방(췌장염)",
      "정기 혈당·프럭토사민 상담",
    ],
    relatedSlugs: ["dog-obesity", "dog-pancreatitis", "dog-cataract"],
  }),
];
