import { guide } from "@/lib/health/guide";
import type { HealthGuide } from "@/lib/health/types";

export const EXOTIC_GUIDES: HealthGuide[] = [
  // 파충류
  guide({
    slug: "reptile-mbd",
    title: "대사성 골질환(MBD)",
    species: ["reptile"],
    kind: "disease",
    system: "metabolic",
    urgency: "soon",
    summary:
      "칼슘·비타민D·UVB 불균형으로 뼈가 약해지는 파충류 대표 질환입니다. 턱 변형·떨림·골절이 나타날 수 있습니다.",
    signals: ["턱·다리 부종·변형", "떨림·무기력", "움직임 감소", "골절"],
    causes: ["칼슘 부족", "UVB 미제공", "온도·조명 환경 불량"],
    homeCare: ["사육 환경을 즉시 점검", "임의 고용량 주사/제는 위험 — 병원"],
    seeVetWhen: ["변형·발작·식욕 소실"],
    prevention: [
      "종에 맞는 UVB·온도 경사",
      "칼슘·비타민 보충 프로토콜",
      "정기 체중·변 상태 기록",
    ],
  }),
  guide({
    slug: "reptile-dysecdysis",
    title: "탈피 부전",
    species: ["reptile"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "오래된 피부가 제대로 벗겨지지 않아 발가락·눈 주변에 남아 괴사 위험이 생깁니다.",
    signals: ["부분 탈피 잔여", "발가락 조임", "눈꺼풀 탁함"],
    causes: ["습도 부족", "영양·기생충", "피부 손상"],
    homeCare: ["종별 적정 습도 회복", "억지로 찢지 말 것"],
    seeVetWhen: ["발가락 변색·부종", "눈 문제"],
    prevention: ["올바른 습도·은신처", "건강 급여", "정기 관찰"],
  }),
  guide({
    slug: "reptile-respiratory",
    title: "파충류 호흡기 감염",
    species: ["reptile"],
    kind: "disease",
    system: "respiratory",
    urgency: "soon",
    summary:
      "콧물·개구호흡·거품은 온도·습도 스트레스와 감염의 신호일 수 있습니다.",
    signals: ["콧물·거품", "개구호흡", "활동·식욕 저하"],
    causes: ["저온", "환기 불량", "세균·바이러스"],
    homeCare: ["온도 경사를 즉시 교정", "임의 항생제 금지"],
    seeVetWhen: ["호흡 이상·식욕 소실"],
    prevention: ["종별 사육 온도 준수", "청결·검역"],
  }),
  guide({
    slug: "reptile-mouth-rot",
    title: "입병(구내염)",
    species: ["reptile"],
    kind: "disease",
    system: "dental",
    urgency: "soon",
    summary:
      "입안 염증·분비물·먹이 거부가 나타납니다. 외상·환경·감염이 겹칩니다.",
    signals: ["입 주변 분비물", "먹이 거부", "부종"],
    causes: ["외상", "저온·위생", "세균"],
    homeCare: ["사육장 청결·온도 점검"],
    seeVetWhen: ["먹는 것을 못할 때"],
    prevention: ["안전한 은신·기질", "적정 환경"],
  }),
  guide({
    slug: "reptile-egg-binding",
    title: "알 정체",
    species: ["reptile"],
    kind: "disease",
    system: "general",
    urgency: "emergency",
    summary:
      "암컷이 알을 낳지 못해 위험한 상태입니다. 무기력·뒷다리 약화가 동반될 수 있습니다.",
    signals: ["산란 자세 반복", "식욕 소실", "팽만·통증"],
    causes: ["칼슘 부족", "산란장 부재", "비만·저온"],
    homeCare: ["산란 환경 제공 시도 + 즉시 병원"],
    seeVetWhen: ["의심되면 응급"],
    prevention: ["번식 전 건강·칼슘 관리", "적절한 산란장"],
  }),
  guide({
    slug: "reptile-burn",
    title: "화상",
    species: ["reptile"],
    kind: "disease",
    system: "environment",
    urgency: "soon",
    summary:
      "열원 접촉으로 복부·다리에 화상이 생깁니다. 핫록/전구 배치 실수가 흔합니다.",
    signals: ["변색·수포", "통증·식욕 저하"],
    causes: ["보호망 없는 열원", "온도 과다"],
    homeCare: ["열원 즉시 차단", "가정 연고 임의 도포 주의"],
    seeVetWhen: ["수포·감염 징후"],
    prevention: ["열원 가드", "온도 측정", "종별 거리 확보"],
  }),
  // 새
  guide({
    slug: "bird-feather-plucking",
    title: "깃털 뽑기",
    species: ["bird"],
    kind: "symptom",
    system: "behavior",
    urgency: "soon",
    summary:
      "의학적 가려움과 심리적 요인이 섞입니다. 피부병·기생충·영양·외로움을 함께 봅니다.",
    signals: ["국소·전신 깃 소실", "과도한 다듬기", "피부 손상"],
    causes: ["피부·기생충", "영양 불균형", "스트레스·권태"],
    homeCare: ["환경 Enrichment", "처벌 금지"],
    seeVetWhen: ["피부 손상·출혈", "갑작스러운 시작"],
    prevention: ["사회성·장난감 로테이션", "완전 사료", "수면·조명 리듬"],
  }),
  guide({
    slug: "bird-crop-stasis",
    title: "소낭 정체",
    species: ["bird"],
    kind: "disease",
    system: "digestive",
    urgency: "emergency",
    summary:
      "소낭이 비워지지 않아 팽만·신냄새·무기력이 생깁니다. 어린 새에서 특히 위험합니다.",
    signals: ["소낭 팽만", "역류", "식욕 저하"],
    causes: ["감염", "이물", "저온·잘못된 포유"],
    homeCare: ["임의 마사지·강제 급여 위험"],
    seeVetWhen: ["즉시"],
    prevention: ["위생적 급여", "적정 온도", "정기 검진"],
  }),
  guide({
    slug: "bird-respiratory",
    title: "새 호흡기 질환",
    species: ["bird"],
    kind: "disease",
    system: "respiratory",
    urgency: "emergency",
    summary:
      "꼬리 흔들 호흡·개구호흡·재채기는 응급에 가깝습니다. 공기가주머니 구조상 빠르게 악화됩니다.",
    signals: ["개구호흡", "꼬리 보빙", "콧물·눈곱", "목소리 변화"],
    causes: ["감염", "분진·연기", "비타민A 부족"],
    homeCare: ["따뜻·조용·즉시 병원"],
    seeVetWhen: ["호흡 이상 = 응급"],
    prevention: ["환기·금연", "영양", "검역"],
  }),
  guide({
    slug: "bird-egg-binding",
    title: "산란 정체(조류)",
    species: ["bird"],
    kind: "disease",
    system: "general",
    urgency: "emergency",
    summary:
      "알이 산도에 걸려 위험합니다. 웅크림·힘주기·다리 약화가 단서입니다.",
    signals: ["산란 자세", "팽만", "무기력"],
    causes: ["칼슘 부족", "과잉 산란", "비만"],
    homeCare: ["가온·안정 + 병원"],
    seeVetWhen: ["즉시"],
    prevention: ["칼슘·광 주기 관리", "번식 자극 조절"],
  }),
  guide({
    slug: "bird-fatty-liver",
    title: "지방간(조류)",
    species: ["bird"],
    kind: "disease",
    system: "metabolic",
    urgency: "soon",
    summary:
      "씨앗 편식·비만과 연관됩니다. 무기력·호흡·복부가 커 보일 수 있습니다.",
    signals: ["비만", "기력 저하", "깃 상태 불량"],
    causes: ["고지방 씨앗", "운동 부족"],
    homeCare: ["급여 전환은 서서히"],
    seeVetWhen: ["식욕 소실·호흡 이상"],
    prevention: ["펠릿 비중", "비행·놀이", "체중 관리"],
  }),
  // 소동물
  guide({
    slug: "small-gi-stasis",
    title: "위장 정체",
    species: ["small"],
    kind: "disease",
    system: "digestive",
    urgency: "emergency",
    summary:
      "토끼 등에서 위장 운동이 멈춰 생명을 위협합니다. 식욕·변 감소가 초기 신호입니다.",
    signals: ["사료·건초 거부", "변 감소·없음", "팽만·통증 자세"],
    causes: ["통증", "스트레스", "털뭉치", "식이 섬유 부족"],
    homeCare: ["즉시 병원 — 가정 대기 금지에 가깝"],
    seeVetWhen: ["변/식욕 이상 = 당일"],
    prevention: ["무제한 건초", "정기 운동", "통증·치과 관리"],
  }),
  guide({
    slug: "small-malocclusion",
    title: "부정교합",
    species: ["small"],
    kind: "disease",
    system: "dental",
    urgency: "soon",
    summary:
      "계속 자라는 치아가 맞지 않아 식사 장애·침 흘림이 생깁니다.",
    signals: ["침", "편식", "체중 감소", "눈물"],
    causes: ["유전", "섬유 부족", "외상"],
    homeCare: ["건초 중심 급여"],
    seeVetWhen: ["식사량 감소"],
    prevention: ["고섬유 식이", "정기 구강 검진"],
  }),
  guide({
    slug: "small-wet-tail",
    title: "웻테일(설사병)",
    species: ["small"],
    kind: "disease",
    system: "digestive",
    urgency: "emergency",
    summary:
      "햄스터 등에서 심한 설사로 항문 주변이 젖습니다. 탈수가 빨라 응급입니다.",
    signals: ["수양성 설사", "축축한 꼬리", "웅크림"],
    causes: ["스트레스", "세균", "식이 급변"],
    homeCare: ["보온·즉시 병원"],
    seeVetWhen: ["즉시"],
    prevention: ["안정된 환경", "위생", "급변 금지"],
  }),
  guide({
    slug: "small-vitamin-c",
    title: "비타민C 결핍",
    species: ["small"],
    kind: "disease",
    system: "metabolic",
    urgency: "soon",
    summary:
      "기니피그처럼 비타민C를 합성하지 못하는 종에서 괴혈병 양상이 나타납니다.",
    signals: ["기력 저하", "관절 통증", "피모 불량", "이빨/잇몸 문제"],
    causes: ["급여 부족", "신선 채소 부족"],
    homeCare: ["즉시 급여 교정 + 병원"],
    seeVetWhen: ["통증·식욕 저하"],
    prevention: ["매일 비타민C 공급원", "올바른 전용 사료"],
  }),
  guide({
    slug: "small-snuffles",
    title: "스너플즈(콧물감염)",
    species: ["small"],
    kind: "disease",
    system: "respiratory",
    urgency: "soon",
    summary:
      "토끼의 상부기도 감염으로 콧물·재채기가 지속됩니다.",
    signals: ["콧물", "재채기", "눈곱", "호흡음"],
    causes: ["세균", "환기·먼지", "스트레스"],
    homeCare: ["먼지 적은 바닥재", "임의 약 금지"],
    seeVetWhen: ["호흡 이상·식욕 저하"],
    prevention: ["환기", "검역", "청결"],
  }),
  guide({
    slug: "small-heatstroke",
    title: "열사병(소동물)",
    species: ["small"],
    kind: "prevention",
    system: "environment",
    urgency: "emergency",
    summary:
      "토끼·기니피그 등은 더위에 취약합니다. 늘어짐·헐떡임은 응급입니다.",
    signals: ["늘어짐", "침", "빠른 호흡", "경련"],
    causes: ["고온", "환기 불량", "직사광선"],
    homeCare: ["서늘한 곳으로 이동, 미지근한 냉각(과도한 얼음 금지) + 병원"],
    seeVetWhen: ["즉시"],
    prevention: ["25℃ 전후 관리(종별)", "여름 냉각 용품", "차 안 금지"],
  }),
  // 관상어
  guide({
    slug: "fish-ich",
    title: "백점병",
    species: ["fish"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "몸에 흰 점이 생기고 비벼대는 행동(플래싱)이 나타납니다. 수온·스트레스와 연관됩니다.",
    signals: ["흰 점", "비비기", "호흡 항진", "무기력"],
    causes: ["원충", "급격한 수온 변화", "밀집"],
    homeCare: ["수질·수온 점검", "검증된 치료 프로토콜"],
    seeVetWhen: ["대량 폐사·호흡 위기"],
    prevention: ["검역", "안정된 수온", "좋은 수질"],
  }),
  guide({
    slug: "fish-fin-rot",
    title: "지느러미 부식",
    species: ["fish"],
    kind: "disease",
    system: "skin",
    urgency: "soon",
    summary:
      "지느러미 끝이 헐고 헐렁해집니다. 수질·세균·공격이 원인입니다.",
    signals: ["지느러미 손상", "백탁·충혈", "위축"],
    causes: ["수질 악화", "세균", "동료 공격"],
    homeCare: ["환수·여과 점검"],
    seeVetWhen: ["급격한 진행·전신 증상"],
    prevention: ["수질 유지", "과밀 금지", "검역"],
  }),
  guide({
    slug: "fish-swim-bladder",
    title: "부레병",
    species: ["fish"],
    kind: "disease",
    system: "general",
    urgency: "soon",
    summary:
      "균형을 못 잡고 뜨거나 가라앉습니다. 변비·감염·기형과 연관될 수 있습니다.",
    signals: ["옆으로 떠 있음", "가라앉음", "이상 유영"],
    causes: ["과식", "변비", "감염", "수질"],
    homeCare: ["급여 조절·완두 등(종별 주의)", "수질 점검"],
    seeVetWhen: ["장기화·호흡 이상"],
    prevention: ["적정 급여", "다양한 식이", "수질"],
  }),
  guide({
    slug: "fish-ammonia",
    title: "수질 악화(암모니아 중독)",
    species: ["fish"],
    kind: "prevention",
    system: "environment",
    urgency: "emergency",
    summary:
      "암모니아·아질산 상승은 급성 폐사의 주범입니다. 헐떡임·붉은 아가미·집단 증상이 단서입니다.",
    signals: ["수면 호흡", "아가미 발적", "집단 무기력", "급사"],
    causes: ["미숙 사이클", "과밀·과식", "여과 실패"],
    homeCare: ["즉시 부분 환수·원인 제거", "테스트 키트로 수치 확인"],
    seeVetWhen: ["대량 폐사 시 원인 분석"],
    prevention: [
      "질소 사이클 완성 후 입수",
      "정기 수질 테스트",
      "과식·과밀 금지",
    ],
  }),
];
